# Generated by Django 5.0 on 2023-12-19 18:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Observatory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fits_image',
            name='ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='fits_image',
            name='NAXIS1',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100000)]),
        ),
        migrations.AlterField(
            model_name='fits_image',
            name='SERIES',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddConstraint(
            model_name='fits_image',
            constraint=models.UniqueConstraint(fields=('DATE_OBS',), name='unique_by_DATE_OBS'),
        ),
    ]
