# Generated by Django 5.0 on 2024-01-16 12:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Observatory', '0002_alter_fits_image_id_alter_fits_image_naxis1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fits_image',
            name='AIRMASS',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000.0)]),
        ),
        migrations.AlterField(
            model_name='fits_image',
            name='AZIMUTH',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(360.0)]),
        ),
        migrations.AlterField(
            model_name='fits_image',
            name='DEC',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)]),
        ),
        migrations.AlterField(
            model_name='fits_image',
            name='DECTRACK',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000.0)]),
        ),
        migrations.AlterField(
            model_name='fits_image',
            name='DEC_PNT',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)]),
        ),
        migrations.AlterField(
            model_name='fits_image',
            name='ELEVATIO',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)]),
        ),
        migrations.AlterField(
            model_name='fits_image',
            name='FILTER',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='fits_image',
            name='GAIN',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AlterField(
            model_name='fits_image',
            name='IMAGETYP',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='fits_image',
            name='MJD_OBS',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100000.0)]),
        ),
        migrations.AlterField(
            model_name='fits_image',
            name='MODE',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='fits_image',
            name='OBJECT_NAME',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fits_image',
            name='OBSERVER',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='fits_image',
            name='PHASE',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(180.0)]),
        ),
        migrations.AlterField(
            model_name='fits_image',
            name='RA',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(360.0)]),
        ),
        migrations.AlterField(
            model_name='fits_image',
            name='RANGE',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1e+27)]),
        ),
        migrations.AlterField(
            model_name='fits_image',
            name='RATRACK',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000.0)]),
        ),
        migrations.AlterField(
            model_name='fits_image',
            name='RA_PNT',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(360.0)]),
        ),
        migrations.AlterField(
            model_name='fits_image',
            name='RD_NOISE',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AlterField(
            model_name='fits_image',
            name='SERIES',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
